services:
  # BoB Testnet
  op-succinct-server-bob-testnet:
    build:
      context: .
      dockerfile: ./proposer/succinct/Dockerfile
    env_file:
      - .env.bobtestnet
    restart: unless-stopped
    ports:
      - "3001:3001"

  op-succinct-proposer-bob-testnet:
    build:
      context: .
      dockerfile: ./proposer/op/Dockerfile.op_proposer
    env_file:
      - .env.bobtestnet
    restart: unless-stopped
    depends_on:
      - op-succinct-server-bob-testnet
    volumes:
      - ./db:/usr/local/bin/dbdata
  
  # Phala Testnet
  op-succinct-server-phala-testnet:
    build:
      context: .
      dockerfile: ./proposer/succinct/Dockerfile
    env_file:
      - .env.phalatestnet
    restart: unless-stopped
    ports:
      - "3002:3002"

  op-succinct-proposer-phala-testnet:
    build:
      context: .
      dockerfile: ./proposer/op/Dockerfile.op_proposer
    env_file:
      - .env.phalatestnet
    restart: unless-stopped
    depends_on:
      - op-succinct-server-phala-testnet
    volumes:
      - ./db:/usr/local/bin/dbdata

  # OP Sepolia
  op-succinct-server-op-sepolia:
    build:
      context: .
      dockerfile: ./proposer/succinct/Dockerfile
    env_file:
      - .env.opsepolia
    restart: unless-stopped
    ports:
      - "3003:3003"

  op-succinct-proposer-op-sepolia:
    build:
      context: .
      dockerfile: ./proposer/op/Dockerfile.op_proposer
    env_file:
      - .env.opsepolia
    restart: unless-stopped
    depends_on:
      - op-succinct-server-op-sepolia
    volumes:
      - ./db:/usr/local/bin/dbdata
